#!bin/sh
IP=thisnode.info
if [ -z `ssh-keygen -F $IP` ]; then
  ssh-keyscan -H $IP >> ~/.ssh/known_hosts
fi
while true; do
    echo "Do you have ip6tables-mod-nat installed?"
    read yn
    case $yn in
        [Yy]* ) echo ""; break;;
        [Nn]* ) ssh root@thisnode.info "opkg update && opkg install ip6tables-mod-nat"; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

echo "Copying Pitbull files..."
scp -r files/* root@thisnode.info:/ && scp -r luasrc/* root@thisnode.info:/usr/lib/lua/luci

ssh root@thisnode.info "chmod +x /www/cgi-bin/client_ip && chmod +x /usr/libexec/rpcd/pirania && chmod +x /www/cgi-bin/error_handler && /etc/init.d/rpcd restart && /etc/init.d/uhttpd restart && wifi down && wifi up"
echo "Preparing the portal app"
npm run install-portal
echo "Done! Setting up"
while true; do
    echo "Do you want to start the captive portal?"
    read yn
    case $yn in
        [Yy]* ) ssh root@thisnode.info "/usr/bin/captive-portal && /etc/init.d/firewall reload && /etc/init.d/firewall-lime reload"; break;;
        [Nn]* ) "Run captive-portal to start"; break;;
        * ) echo "Please answer yes or no.";;
    esac
done