#!/usr/bin/lua

print ('Status: 200 ; Location "http://10.5.54.1/app"; Content-type text/html\r\n\r\n')

print([[
<!doctype html>
<html>
  <head>
    <title>Pirania - Captive Portal</title>
    <meta http-equiv="Refresh" content="0; url=http://thisnode.info/app">

    <!-- If the meta tag doesn't work, try JavaScript to redirect. -->

    <script type="text/javascript">
      window.location.href = "http://thisnode.info/app"
    </script>
  </head>

  <body>
    <!-- If JavaScript doesn't work, give a link to click on to redirect. -->

    <p><a href='http://thisnode.info/app'>ENTER</a></p>
  </body>
</html>
]])

-- print ("Location http://thisnode.info\r\n")