#!/usr/bin/lua

local json = require 'luci.json'

print ("Content-type: application/json\n")
local ip = os.getenv('REMOTE_ADDR')

local function get_mac_from_ip(ip)
    local command = 'ping -i 0.2 -w 0.2 -c 1 '..ip..' >/dev/null; cat /proc/net/arp | grep '..ip..' | grep br-lan | awk \'{print $4}\' | head -c -1'
    fd = io.popen(command, 'r')
    local output = fd:read('*all')
    fd:close()
    return output
end

local function check_voucher(ip)
    local mac, command

    mac = get_mac_from_ip( ip )

    command = 'cat /tmp/validmacs | grep -o '..mac..' | wc -l'
    fd = io.popen(command, 'r')
    local output = tonumber(fd:read('*all'))
    fd:close()
    return output
end

local mac = get_mac_from_ip(ip)
local valid = check_voucher(ip)
local response = {}
response.ip = ip
response.mac = mac
if valid == 0 then response.valid = false
else response.valid = true
end

print(json.encode(response))
