#!/usr/bin/lua

print ("Content-type: text/html\n\n")

print ([[
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Pirania - Captive Protal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <h1>Hi! Im html!</h1>
</body>
</html>
]])